@startuml

class Estacionamento {
  - nome: string
  - capacidadeMaxima: number
  
}

class Vaga {
  - numero: number
  - tipo: string
}

class Cliente {
  - nome: string
  - cpf: string
}

class Veiculo {
  - placa: string
  - tipo: string
}

class Registro {
  - dataEntrada: datetime
  - dataSaida: datetime | None
  
  + calcularTempo()
}

Estacionamento --> Vaga
Registro --> Vaga
Cliente --> Veiculo
Veiculo --> Registro

@enduml
